### ISSUE TITLE
基于作者的做了一些优化，不需要频繁的输入url前缀，非常感谢

### ISSUE THREAD

**Issue by ivesyi** [gaboolic/cloudflare-reverse-fast#12]
基于作者的做了一些优化，不需要频繁的输入url前缀，非常感谢作者大大。
https://github.com/ivesyi/cf-worker-proxy/blob/main/_worker.js

**Comment by gaboolic** [comment]
不错，我倒没想到还能修改response header的location
越来越行了

**Comment by hhhaiai** [comment]
666

**Comment by ekworp** [comment]
能重新发一下吗

**Comment by kokojacket** [comment]
+1
