### ISSUE TITLE
现在项目跑不起来了， work 只支持 ES module 语法，刚刚全部改好了，大家自取

### ISSUE THREAD

**Issue by WBinBin001** [gaboolic/cloudflare-reverse-fast#26]
项目地址
https://github.com/WBinBin001/cloudflare-reverse-proxy

**Comment by gaboolic** [comment]
我刚测试了一下我之前搭建的还能用，现在是新创建的不能用了吗

**Comment by WBinBin001** [comment]
是的， 现在新建的用不了了，大佬有时间改一下，我昨天改成 ES module 了，你看下

**Comment by gaboolic** [comment]
我新建了一个worker，用现在的代码是可以工作的

**Comment by martjay** [comment]
Uncaught SyntaxError: Unexpected token 'export' at worker.js:117
